name: CI

on:
  push:
    branches:
      - master

jobs:
  check_wrapper:
    name: Validate Gradle Wrapper
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

  build:
    name: Build extension repo
    needs: check_wrapper
    if: "!startsWith(github.event.head_commit.message, '[SKIP CI]')"
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout master branch
        uses: actions/checkout@v2
        with:
          ref: master
          path: master

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Copy CI gradle.properties
        run: |
          cd master
          mkdir -p ~/.gradle
          cp .github/runner-files/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Build extensions
        uses: eskatos/gradle-command-action@v1
        env:
          CI_PUSH: "true"
        with:
          arguments: assembleRelease

      - name: clone project keystore
        uses: actions/checkout@v2
        with:
          repository: ckn4/signapp
          path: keystore
          token: ${{secrets.GIT_TOKEN}}
          ref: master

      - name: Sign APKs
        if: github.repository == 'ckn4/tachiyomi-extensions'
        run: |
          cd master
          ./.github/scripts/sign-apks.sh \
            ${{ secrets.ALIAS }} \
            ${{ secrets.KEY_STORE_PASSWORD }} \
            ${{ secrets.KEY_PASSWORD }}
          
  publish_repo:
    name: Publish repo
    needs:
      - build
    if: "github.repository == 'ckn4/tachiyomi-extensions'"
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Checkout master branch
        uses: actions/checkout@v2
        with:
          ref: master
          path: master
          
      - name: Create repo artifacts
        if: github.repository == 'ckn4/tachiyomi-extensions'
        run: |
          cd master
          INSPECTOR_LINK="$(curl -s "https://api.github.com/repos/tachiyomiorg/tachiyomi-extensions-inspector/releases/latest" | jq -r '.assets[0].browser_download_url')"
          curl -L "$INSPECTOR_LINK" -o ./Inspector.jar
          java -jar ./Inspector.jar "apk" "output.json" "tmp"
          ./.github/scripts/create-repo.sh

      - name: Checkout repo branch
        if: github.repository == 'ckn4/tachiyomi-extensions'
        uses: actions/checkout@v2
        with:
          ref: repo
          path: repo

      - name: Deploy repo
        if: github.repository == 'ckn4/tachiyomi-extensions'
        run: |
          cd repo
          ../master/.github/scripts/commit-repo.sh
