name: CI

on:
  push:
    branches:
      - master

jobs:
  check_wrapper:
    name: Validate Gradle Wrapper
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
          all_but_latest: true    
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

  build:
    name: Build extension repo
    needs: check_wrapper
    strategy:
      matrix:
        lang: [all, en, ja, zh]    
    if: "!startsWith(github.event.head_commit.message, '[SKIP CI]')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master branch
        uses: actions/checkout@v2
        with:
          ref: master
          path: master

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Copy CI gradle.properties
        run: |
          cd master
          mkdir -p ~/.gradle
          cp .github/runner-files/ci-gradle.properties ~/.gradle/gradle.properties
          echo ${{ secrets.SIGNING_KEY }} | base64 -d > signingkey.jks

      - name: Build "${{ matrix.lang }}" extensions
        uses: gradle/gradle-command-action@v2
        env:
          CI_MATRIX_LANG: ${{ matrix.lang }}
          ALIAS: ${{ secrets.ALIAS }}
          KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        with:
          build-root-directory: master
          wrapper-directory: master
          arguments: assembleRelease
          
      - name: Upload "${{ matrix.lang }}" APKs
        uses: actions/upload-artifact@v2
        if: "github.repository == 'ckn4/tachiyomi-extensions'"
        with:
          name: "individual-${{ matrix.lang }}-apks"
          path: "**/*.apk"
          retention-days: 1

      - name: Clean up CI files
        run: |
          cd master
          rm signingkey.jks
          
  publish_repo:
    name: Publish repo
    needs:
      - build
    if: "github.repository == 'ckn4/tachiyomi-extensions'"
    runs-on: ubuntu-latest
    steps:
      - name: Download APK artifacts
        uses: actions/download-artifact@v2
        with:
          path: ~/apk-artifacts

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Checkout master branch
        uses: actions/checkout@v2
        with:
          ref: master
          path: master
          
      - name: Create repo artifacts
        if: github.repository == 'ckn4/tachiyomi-extensions'
        run: |
          cd master
          chmod +x .github/scripts/move-apks.sh
          ./.github/scripts/move-apks.sh
          INSPECTOR_LINK="$(curl -s "https://api.github.com/repos/tachiyomiorg/tachiyomi-extensions-inspector/releases/latest" | jq -r '.assets[0].browser_download_url')"
          curl -L "$INSPECTOR_LINK" -o ./Inspector.jar
          java -jar ./Inspector.jar "apk" "output.json" "tmp"
          ./.github/scripts/create-repo.sh

      - name: Checkout repo branch
        if: github.repository == 'ckn4/tachiyomi-extensions'
        uses: actions/checkout@v2
        with:
          ref: repo
          path: repo

      - name: Deploy repo
        if: github.repository == 'ckn4/tachiyomi-extensions'
        run: |
          cd repo
          ../master/.github/scripts/commit-repo.sh
